package com.danil.blackswordsman;
import java.util.ArrayList;
public final class V6RegressionSmoke {
 static class Store implements SnapshotCodec.Store {GameWorld.Progress progress;byte[] bytes;public GameWorld.Progress load(){return progress;}public void save(GameWorld.Progress p){progress=p.copy();}public void clear(){progress=null;bytes=null;}public byte[] loadCheckpoint(){return bytes;}public void saveCheckpoint(byte[] b){bytes=b;}public void clearCheckpoint(){bytes=null;}}
 static class Motion implements GameWorld.MotionInput {public float getTiltX(){return 1;}public float getTiltY(){return -1;}public float consumeGyroYaw(){return 0;}public float consumeGyroPitch(){return 0;}public boolean hasGyroscope(){return true;}public boolean hasAccelerometer(){return true;}public void calibrate(){}}
 static void check(boolean v,String m){if(!v)throw new AssertionError(m);}
 static void near(float a,float b,float tolerance,String m){check(Math.abs(a-b)<tolerance,m+" "+a+" / "+b);}
 static GameWorld start(GameInput in,Store s){GameWorld w=new GameWorld(in,new Motion(),s);in.pressAction();w.update(.02f);for(int i=0;i<w.currentChapter().intro.length;i++){in.pressAction();w.update(.02f);}check(w.mode==GameWorld.PLAYING,"starts");return w;}
 static void seconds(GameWorld w,float t){for(int i=0;i<(int)(t*60);i++)w.update(1f/60);}
 public static void main(String[] args)throws Exception {
  for(int rate:new int[]{20,30,60,120}){SimulationClock c=new SimulationClock();final float[] sum={0};for(int i=0;i<rate*3;i++)c.advance(1f/rate,new SimulationClock.Step(){public void simulate(float dt){sum[0]+=dt;}});near(sum[0],3,.009f,"clock at "+rate);}
  TouchOwnership touch=new TouchOwnership();touch.sync(GameWorld.PLAYING,0);check(touch.acquire(7,true)&&touch.acquire(2,false),"multitouch owns ids");check(!touch.release(2)&&touch.joystick==7,"camera up keeps stick");touch.sync(GameWorld.PAUSED,1);check(touch.joystick==-1&&touch.camera==-1,"pause drops every pointer");touch.overlayDown(2,GameWorld.PAUSED,600,370);check(!touch.overlayUp(2,GameWorld.MENU,600,370),"cross-mode release cannot click");touch.sync(GameWorld.PLAYING,2);touch.acquire(4,true);touch.reset();check(touch.joystick==-1,"cancel ownership");
  check(ControlMap.battle(1238-24,126+16,24,16)==ControlMap.PAUSE,"safe inset hit");check(ControlMap.battle(690,650,0)==ControlMap.JUMP&&ControlMap.battle(745,680,0)==ControlMap.ROTATE,"new controls mapped");
  GameInput input=new GameInput();Store store=new Store();GameWorld w=start(input,store);w.enemies.clear();w.player.invulnerable=10000;float x=w.player.x,z=w.player.z;seconds(w,.5f);near(w.player.x,x,.01f,"idle x");near(w.player.z,z,.01f,"idle z");
  input.moveY=-1;input.pressLight();input.resetAll();check(!input.consumeLight()&&input.moveY==0,"reset clears buffered attack and stick");
  input.pressPause();w.update(.02f);float time=w.surreal.time;seconds(w,.5f);near(w.surreal.time,time,.001f,"pause timers");input.pressAction();w.update(.02f);
  // Round trip the complete graph, including shared body references and temporary effects.
  w.player.hp=123;w.collectPickup(PlayerEffects.HOUND);w.quest.stage=1;w.surreal.props.get(100).body.x=41.25f;byte[] snapshot=SnapshotCodec.encode(w);GameWorld loaded=new GameWorld(new GameInput(),new Motion(),new Store());check(SnapshotCodec.restore(loaded,snapshot),"checkpoint restore");near(loaded.player.hp,123,.001f,"health restore");near(loaded.surreal.props.get(100).body.x,41.25f,.001f,"world restore");check(loaded.effects.form==PlayerEffects.HOUND&&loaded.quest.stage==1,"effects and quest restore");snapshot[30]^=1;check(!SnapshotCodec.restore(loaded,snapshot),"checksum rejects corruption");
  GameWorld.Actor enemy=new GameWorld.Actor();enemy.x=0;enemy.y=0;enemy.z=3;enemy.height=2;enemy.radius=.5f;enemy.hp=enemy.maxHp=1000;enemy.spawnTime=0;enemy.type=GameWorld.BANDIT;w.enemies.clear();w.enemies.add(enemy);w.physics.bodies.clear();w.effects.clear();w.effects.apply(w.player,w.getProgressCopy());w.player.x=0;w.player.y=0;w.player.z=0;w.player.yaw=0;
  GameWorld.Projectile shot=new GameWorld.Projectile();shot.friendly=true;shot.x=0;shot.y=1;shot.z=2.7f;shot.vz=.2f;shot.radius=.3f;shot.damage=20;shot.pierce=10;shot.life=3;w.projectiles.add(shot);CombatSystem.projectiles(w,.01f);float health=enemy.hp;for(int i=0;i<30;i++)CombatSystem.projectiles(w,.01f);near(enemy.hp,health,.001f,"piercing cannot repeat a target");check(health<1000,"projectile hit");
  check(Float.isInfinite(CollisionMath.segmentActor(0,4,0,0,4,6,enemy,.1f)),"high projectile misses capsule");
  PhysicsWorld.Body wall=w.physics.createStatic(PhysicsWorld.RUIN,0,1,1.5f,2,1,.2f);check(!CombatSystem.visible(w,w.player,enemy),"solid wall blocks combat");wall.solid=false;check(CombatSystem.visible(w,w.player,enemy),"open path visible");
  PhysicsWorld p=new PhysicsWorld();p.resetForChapter(1,1);p.bodies.clear();GameWorld.Actor player=new GameWorld.Actor();player.height=2;player.radius=.5f;player.x=10;player.z=10;player.hp=100;
  PhysicsWorld.Body bottom=p.createStatic(PhysicsWorld.CRATE,0,.58f,0,.5f,.5f,.5f),top=p.createToy(SurrealCatalog.ITEMS[40],0,0);top.hx=top.hy=top.hz=.5f;top.y=3;top.shape=PhysicsWorld.SHAPE_BOX;top.vx=top.vy=top.vz=0;top.restitution=0;
  for(int i=0;i<360;i++)p.update(1f/120,player,new ArrayList<GameWorld.Actor>());near(top.y,bottom.y+1,.08f,"box rests on another box");
  player.x=0;player.z=0;player.y=3.2f;player.vy=0;for(int i=0;i<240;i++)p.update(1f/120,player,new ArrayList<GameWorld.Actor>());check(player.y>1.5f&&player.grounded,"actor stands on stack");
  // Every skin is valid at rest, has outward faces, normalized weights and identity bind transform.
  GameWorld.Actor model=new GameWorld.Actor();model.height=2.1f;model.radius=.52f;model.speed=5;model.type=-1;SkinGeometry skin=new SkinGeometry(model,true);CharacterSkeleton.Pose pose=new CharacterSkeleton.Pose();CharacterSkeleton.sample(model,0,pose);float[] palette=new float[256];skin.palette(pose,0,palette);for(int i=0;i<16;i++){near(palette[i*16],1,.001f,"bind identity");near(palette[i*16+12],0,.001f,"bind translation");}for(int i=0;i<skin.vertices.length;i+=16)near(skin.vertices[i+13]+skin.vertices[i+14],1,.001f,"weights");
  int wrong=0;for(int i=0;i<skin.indices.length;i+=3){int a=(skin.indices[i]&65535)*16,b=(skin.indices[i+1]&65535)*16,c=(skin.indices[i+2]&65535)*16;float[] v=skin.vertices;float ax=v[b]-v[a],ay=v[b+1]-v[a+1],az=v[b+2]-v[a+2],bx=v[c]-v[a],by=v[c+1]-v[a+1],bz=v[c+2]-v[a+2];float dot=(ay*bz-az*by)*(v[a+3]+v[b+3]+v[c+3])+(az*bx-ax*bz)*(v[a+4]+v[b+4]+v[c+4])+(ax*by-ay*bx)*(v[a+5]+v[b+5]+v[c+5]);if(dot<-.000001f)wrong++;}check(wrong==0,"skin outward faces "+wrong);
  System.out.println("V6RegressionSmoke OK: clock, idle/reset/pause, checkpoints+CRC, capsule/wall/projectiles, stacking, actor support, weighted skin");
 }
}
