package com.danil.blackswordsman;
public final class V7CreaturesSmoke {
 static void check(boolean v,String m){if(!v)throw new AssertionError(m);}
 static GameWorld world(){GameWorld w=V6RegressionSmoke.start(new GameInput(),new V6RegressionSmoke.Store());w.enemies.clear();w.physics.bodies.clear();w.physics.joints.clear();w.player.invulnerable=10000;return w;}
 public static void main(String[] args)throws Exception{
  for(int type=0;type<33;type++){GameWorld w=world();GameWorld.Actor a=w.spawnCreature(type,3,5);check(a.category>=0&&a.category<=2&&a.category==CreatureSystem.category(type),"category "+type);}
  for(int type=25;type<=32;type++){GameWorld w=world();GameWorld.Actor a=w.spawnCreature(type,0,13);a.specialCooldown=0;int before=w.projectiles.size();for(int i=0;i<160;i++)CreatureSystem.update(w,a,1f/120);check(a.abilityCount>0,"unique ability executes "+type);if(type==GameWorld.MIRE_SPITTER||type==GameWorld.SENTRY||type==GameWorld.ALIEN)check(w.projectiles.size()>before,"projectile ability "+type);if(type==GameWorld.STORM_SPIRIT)check(!w.particles.isEmpty(),"lightning impact");if(type==GameWorld.GROVE_WARDEN)check(a.shieldTime>0,"warden shield");}
  GameWorld w=world();UfoEncounters.Landing l=w.encounters.landings.get(0);w.player.x=l.ship.x;w.player.z=l.ship.z;w.player.y=w.physics.terrainHeight(w.player.x,w.player.z);for(int i=0;i<8*120;i++)w.encounters.update(w,1f/120);check(l.state==2&&l.visitors.size()==3,"three visitors descend and land");for(GameWorld.Actor a:l.visitors)check(!a.hovering&&a.peaceful,"neutral visitor on ground");
  byte[] snapshot=SnapshotCodec.encode(w);GameWorld restored=world();check(SnapshotCodec.restore(restored,snapshot),"landing snapshot");check(restored.encounters.landings.get(0).visitors.get(0)==restored.enemies.get(0),"visitor identity persisted");for(int i=0;i<40*120;i++)w.encounters.update(w,1f/120);check(l.state==0&&l.cycles==1&&l.visitors.isEmpty(),"visitors return to ship");
  w=world();GameWorld.Actor alien=w.spawnCreature(GameWorld.ALIEN,0,9);alien.peaceful=true;w.damageEnemy(alien,2,0,0,0);check(!alien.peaceful,"visitor only becomes hostile after attack");
  w=world();w.worldVersion=6;w.encounters=null;while(w.surreal.ufos.size()>4){w.physics.bodies.remove(w.surreal.ufos.remove(w.surreal.ufos.size()-1));}while(w.surreal.pickups.size()>120)w.surreal.pickups.remove(w.surreal.pickups.size()-1);snapshot=SnapshotCodec.encode(w);snapshot[7]=6;restored=world();check(SnapshotCodec.restore(restored,snapshot)&&restored.worldVersion==8&&restored.encounters.landings.size()==10&&restored.surreal.pickups.size()==192,"v6 migration extends old checkpoint");
  GameInput input=new GameInput();w=V6RegressionSmoke.start(input,new V6RegressionSmoke.Store());w.player.x=282;w.player.z=26;w.player.invulnerable=10000;w.update(.02f);boolean mechanical=false,animal=false;for(GameWorld.Actor a:w.enemies)mechanical|=a.category==CreatureSystem.MECHANICAL;for(GameWorld.Neutral n:w.wildlife)animal|=n.type>=GameWorld.FISH;check(mechanical&&animal,"new regions spawn new fauna and machinery");
  for(int i=0;i<RegionLayout.PLACES.length;i++){float[] q=RegionLayout.PLACES[i];PhysicsWorld p=new PhysicsWorld();p.resetForChapter(0,0);p.streamAround(q[0],q[1]);boolean structure=false;for(PhysicsWorld.Body b:p.bodies)if(b.streamed&&(b.kind==PhysicsWorld.STONE_WALL||b.kind==PhysicsWorld.PALM||b.kind==PhysicsWorld.PLANK))structure=true;check(structure,"usable place "+i);}
  System.out.println("V7CreaturesSmoke OK: 33 nature definitions, eight distinct abilities, neutral UFO descent/observation/ascent, save identity, v6 migration, wildlife, 24 places");
 }
}
