package com.danil.blackswordsman;
public final class V8AnimationSmoke {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}static void near(float a,float b,float eps,String s){check(Math.abs(a-b)<eps,s+": "+a+" / "+b);}static float length(CharacterSkeleton.Pose p,int a,int b){float x=p.x[a]-p.x[b],y=p.y[a]-p.y[b],z=p.z[a]-p.z[b];return (float)Math.sqrt(x*x+y*y+z*z);}
 public static void main(String[] args)throws Exception{
  GameWorld.Actor a=new GameWorld.Actor();a.height=2.1f;a.radius=.52f;a.speed=5;a.grounded=true;a.vz=5;AnimationSystem.update(a,.01f);float initial=a.gaitPhase;for(int i=0;i<120;i++)AnimationSystem.update(a,1f/120);near(a.gaitPhase,initial,.0001f,"wall blocked actor does not walk in place");near(a.animationSpeed,0,.001f,"resolved speed zero");for(int i=0;i<120;i++){a.z+=5f/120;AnimationSystem.update(a,1f/120);}check(a.gaitPhase>10&&a.animationSpeed>.9f,"distance drives stride");a.grounded=false;a.vy=-2;AnimationSystem.update(a,.01f);a.grounded=true;AnimationSystem.update(a,.01f);check(a.landingTime>.3f,"landing compression");
  CharacterSkeleton.Pose p=new CharacterSkeleton.Pose();for(int axis=0;axis<3;axis++){p.x[0]=p.y[0]=p.z[0]=0;p.x[2]=axis==0?5:0;p.y[2]=axis==1?5:0;p.z[2]=axis==2?5:0;AnimationSystem.joint(p,0,1,2,.7f,.6f,axis==0?1:0,axis==1?1:0,axis==2?1:0);near(length(p,0,1),.7f,.001f,"IK upper bone even with parallel pole");near(length(p,1,2),.6f,.001f,"IK lower bone even with parallel pole");}
  for(int type=-1;type<33;type++){a=new GameWorld.Actor();a.type=type;if(type>=0)EnemyDefinitions.apply(a,type,1);else{a.height=2.1f;a.radius=.52f;}a.speed=5;SkinGeometry high=new SkinGeometry(a,true),low=new SkinGeometry(a,false);check(high.vertices.length>low.vertices.length,"LOD "+type);check(high.vertices.length/16<65535,"index budget "+type);for(int i=0;i<high.vertices.length;i+=16){int surface=(int)Math.floor(high.vertices[i+10]/2);check(surface>=0&&surface<12,"surface index "+type);near(high.vertices[i+13]+high.vertices[i+14],1,.001f,"weights");}
   for(int state=0;state<6;state++){a.animationSpeed=state==0?0:1;a.gaitPhase=1.4f;a.grounded=state<3;a.motionReady=true;a.attackTime=state==2?.48f:0;a.attackDuration=.82f;a.attackKind=5;a.attackBlend=state==2?1:0;a.swimming=state==4;a.flying=state==5;a.landingTime=state==1?.2f:0;CharacterSkeleton.sample(a,.3f,p);for(int i=0;i<17;i++)check(!Float.isNaN(p.x[i]+p.y[i]+p.z[i]),"finite pose "+type+"/"+state);if(!CharacterSkeleton.isBeast(type)){near(length(p,5,6),a.height*.17f,.001f,"arm length");near(length(p,6,7),a.height*.17f,.001f,"forearm length");}}
  }
  check(CloudField.noise().length==32768&&CloudField.envelope(60)==0&&CloudField.envelope(100)>0&&CloudField.envelope(140)==0,"bounded volumetric density");check(CloudField.steps(1)==16&&CloudField.steps(3)==32,"adaptive cloud cost");java.util.HashSet<Integer> textures=new java.util.HashSet<Integer>();for(int i=0;i<12;i++){byte[][] tex=SurfaceLibrary.layer(i);check(tex[0].length==512*512*4&&tex[1].length==tex[0].length,"material dimensions");textures.add(java.util.Arrays.hashCode(tex[0]));for(int k=0;k<tex[1].length;k+=4096){float nx=(tex[1][k]&255)/127.5f-1,ny=(tex[1][k+1]&255)/127.5f-1,nz=(tex[1][k+2]&255)/127.5f-1;near(nx*nx+ny*ny+nz*nz,1,.04f,"normal map unit vector");}}check(textures.size()==12,"all materials differ");
  System.out.println("V8AnimationSmoke OK: blocked locomotion, landing, fixed-length IK, 34 skins / 6 states, material maps, bounded 3D cloud inputs");
 }
}
