package com.danil.blackswordsman;
import java.util.*;
public final class V8NatureSmoke {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}static GameWorld world(){GameWorld w=V6RegressionSmoke.start(new GameInput(),new V6RegressionSmoke.Store());w.enemies.clear();w.physics.bodies.clear();w.physics.joints.clear();w.projectiles.clear();return w;}
 public static void main(String[] args)throws Exception{
  check(FloraCatalog.NAMES.length==48,"48 named flora species");HashSet<Integer> hashes=new HashSet<Integer>();for(int id=0;id<48;id++){ToyGeometry.Data mesh=FloraGeometry.build(id,true),low=FloraGeometry.build(id,false);check(mesh.parts>2&&mesh.vertices.length>low.vertices.length,"detailed flora "+id);check(mesh.vertices.length/9<65535,"flora index budget");for(float f:mesh.vertices)check(!Float.isNaN(f)&&!Float.isInfinite(f),"finite flora");hashes.add(Arrays.hashCode(mesh.vertices));}check(hashes.size()==48,"distinct flora geometry/color");
  int dominant=0;Random r=new Random(8);for(int i=0;i<1000;i++){int region=FloraCatalog.region(0,80,60);if(FloraCatalog.select(0,80,60,r)/4==region)dominant++;}check(dominant>800,"regional predominance");GameWorld w=world();w.flora.update(w,.02f);check(w.flora.plants.size()>250&&w.flora.plants.size()<=818,"dense forest bounded population");HashSet<Integer> powers=new HashSet<Integer>();for(FloraWorld.Plant p:w.flora.plants)if(p.species>=24&&p.species<32)powers.add(p.species);check(powers.size()==8,"all powers discoverable near opening");
  FloraWorld.Plant picked=null;for(FloraWorld.Plant p:w.flora.plants)if(p.species==24){picked=p;break;}w.player.x=picked.x;w.player.y=picked.y;w.player.z=picked.z;w.flora.update(w,0);check(w.flora.interact(w)&&w.mushrooms.active(0),"action collects power");long id=picked.id;check(w.flora.harvested.containsKey(id)&&!w.flora.visible(picked),"harvest does not duplicate");w.player.x=350;w.player.z=100;w.flora.stream(w);check(w.flora.plants.size()<=818,"distant stream bounded");w.player.x=picked.x;w.player.z=picked.z;w.flora.stream(w);check(!w.flora.visible(picked),"harvest persisted across chunk reload");
  w=world();w.mushrooms.activate(MushroomEffects.FLIGHT,w);float floor=w.player.y;for(int i=0;i<360;i++){w.mushrooms.update(w,1f/120);w.physics.update(1f/120,w.player,w.enemies);}check(w.player.y>floor+2.5f&&w.player.flying,"actual upward flight");float roof=w.player.y+2.4f;w.physics.createStatic(PhysicsWorld.ROOF,w.player.x,roof,w.player.z,4,.3f,4);w.player.flightY=roof+3;for(int i=0;i<360;i++){w.mushrooms.update(w,1f/120);w.physics.update(1f/120,w.player,w.enemies);}check(w.player.y+w.player.height<roof+.15f,"flight collides with roof");w.mushrooms.timer[1]=.001f;w.mushrooms.update(w,.01f);check(!w.player.flying&&w.player.featherTime>6,"flight expiry gentle descent");
  w=world();PhysicsWorld.Body toy=w.physics.createToy(SurrealCatalog.ITEMS[5],w.player.x+4,w.player.z);toy.y=w.player.y+.75f;toy.vx=toy.vz=toy.vy=0;w.mushrooms.activate(MushroomEffects.MAGNET,w);w.mushrooms.update(w,.1f);check(toy.vx<0,"magnet pulls actual physical body");toy.vx=0;w.mushrooms.activate(MushroomEffects.REPULSE,w);w.mushrooms.update(w,.1f);check(toy.vx>0&&!w.mushrooms.active(2),"repulsion and magnet mutually exclusive");
  GameWorld.Actor enemy=w.spawnCreature(GameWorld.SENTRY,w.player.x,w.player.z+4);enemy.spawnTime=0;enemy.specialCooldown=0;w.mushrooms.activate(MushroomEffects.PEACE,w);java.lang.reflect.Method ai=GameWorld.class.getDeclaredMethod("updateEnemy",GameWorld.Actor.class,float.class);ai.setAccessible(true);int shots=w.projectiles.size();for(int i=0;i<600;i++)ai.invoke(w,enemy,1f/120);check(w.projectiles.size()==shots&&!enemy.strikePending,"peace stops mechanical attacks");w.mushrooms.attack();check(!w.mushrooms.active(0),"deliberate attack breaks peace");w.mushrooms.activate(MushroomEffects.CHRONO,w);w.mushrooms.update(w,.1f);check(enemy.slowTime>0&&toy.stasis>0,"chrono affects creatures and bodies");w.player.hp=100;w.player.poisonTime=9;w.mushrooms.activate(MushroomEffects.HEAL,w);w.mushrooms.update(w,1);check(w.player.hp>103&&w.player.poisonTime==0,"healing and cleanse");w.mushrooms.activate(6,w);w.mushrooms.activate(7,w);check(w.mushrooms.status(0).length()>0,"visible timers");
  byte[] data=SnapshotCodec.encode(w);GameWorld load=world();check(SnapshotCodec.restore(load,data)&&load.mushrooms.timer[7]==w.mushrooms.timer[7],"effects saved");w.mode=GameWorld.PAUSED;float timer=w.mushrooms.timer[7];w.update(.1f);check(w.mushrooms.timer[7]==timer,"powers pause");
  System.out.println("V8NatureSmoke OK: 48 distinct flora, forest density, region bias, collection/regrowth, 8 powers, collision-aware flight, forces, peace, pause and save");
 }
}
