package com.danil.blackswordsman;
import android.opengl.GLES30;
import android.opengl.Matrix;
import java.nio.ByteBuffer;
/** Low-resolution ray-marched cloud volume composited behind opaque geometry. */
public final class CloudRenderer {
 private ShaderProgram volume,copy;private final int[] noise=new int[1],fbo=new int[1],color=new int[1],vao=new int[1],previous=new int[1];private int width,height;private final float[] inverse=new float[16];
 public CloudRenderer(String version){volume=new ShaderProgram(version+VERTEX,version+FRAGMENT);copy=new ShaderProgram(version+VERTEX,version+COPY);GLES30.glGenVertexArrays(1,vao,0);GLES30.glGenTextures(1,noise,0);GLES30.glBindTexture(GLES30.GL_TEXTURE_3D,noise[0]);byte[] data=CloudField.noise();ByteBuffer b=ByteBuffer.allocateDirect(data.length);b.put(data).position(0);GLES30.glTexImage3D(GLES30.GL_TEXTURE_3D,0,GLES30.GL_R8,32,32,32,0,GLES30.GL_RED,GLES30.GL_UNSIGNED_BYTE,b);GLES30.glTexParameteri(GLES30.GL_TEXTURE_3D,GLES30.GL_TEXTURE_MIN_FILTER,GLES30.GL_LINEAR);GLES30.glTexParameteri(GLES30.GL_TEXTURE_3D,GLES30.GL_TEXTURE_MAG_FILTER,GLES30.GL_LINEAR);for(int key:new int[]{GLES30.GL_TEXTURE_WRAP_S,GLES30.GL_TEXTURE_WRAP_T,GLES30.GL_TEXTURE_WRAP_R})GLES30.glTexParameteri(GLES30.GL_TEXTURE_3D,key,GLES30.GL_REPEAT);}
 public void draw(float[] vp,float x,float y,float z,float time,int quality,int w,int h){GLES30.glGetIntegerv(GLES30.GL_FRAMEBUFFER_BINDING,previous,0);int divisor=quality>=3?2:3,nw=Math.max(160,w/divisor),nh=Math.max(90,h/divisor);if(nw!=width||nh!=height){releaseBuffer();width=nw;height=nh;GLES30.glGenTextures(1,color,0);GLES30.glBindTexture(GLES30.GL_TEXTURE_2D,color[0]);GLES30.glTexImage2D(GLES30.GL_TEXTURE_2D,0,GLES30.GL_RGBA8,width,height,0,GLES30.GL_RGBA,GLES30.GL_UNSIGNED_BYTE,null);GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D,GLES30.GL_TEXTURE_MIN_FILTER,GLES30.GL_LINEAR);GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D,GLES30.GL_TEXTURE_MAG_FILTER,GLES30.GL_LINEAR);GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D,GLES30.GL_TEXTURE_WRAP_S,GLES30.GL_CLAMP_TO_EDGE);GLES30.glTexParameteri(GLES30.GL_TEXTURE_2D,GLES30.GL_TEXTURE_WRAP_T,GLES30.GL_CLAMP_TO_EDGE);GLES30.glGenFramebuffers(1,fbo,0);GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER,fbo[0]);GLES30.glFramebufferTexture2D(GLES30.GL_FRAMEBUFFER,GLES30.GL_COLOR_ATTACHMENT0,GLES30.GL_TEXTURE_2D,color[0],0);if(GLES30.glCheckFramebufferStatus(GLES30.GL_FRAMEBUFFER)!=GLES30.GL_FRAMEBUFFER_COMPLETE)throw new IllegalStateException("Cloud target incomplete");}
 GLES30.glDisable(GLES30.GL_DEPTH_TEST);GLES30.glDepthMask(false);GLES30.glDisable(GLES30.GL_BLEND);GLES30.glDisable(GLES30.GL_CULL_FACE);GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER,fbo[0]);GLES30.glViewport(0,0,width,height);volume.use();Matrix.invertM(inverse,0,vp,0);GLES30.glUniformMatrix4fv(volume.uniform("uInverse"),1,false,inverse,0);GLES30.glUniform3f(volume.uniform("uCamera"),x,y,z);GLES30.glUniform1f(volume.uniform("uTime"),time);GLES30.glUniform1i(volume.uniform("uSteps"),CloudField.steps(quality));GLES30.glActiveTexture(GLES30.GL_TEXTURE3);GLES30.glBindTexture(GLES30.GL_TEXTURE_3D,noise[0]);GLES30.glUniform1i(volume.uniform("uNoise"),3);GLES30.glBindVertexArray(vao[0]);GLES30.glDrawArrays(GLES30.GL_TRIANGLES,0,3);
 GLES30.glBindFramebuffer(GLES30.GL_FRAMEBUFFER,previous[0]);GLES30.glViewport(0,0,w,h);copy.use();GLES30.glActiveTexture(GLES30.GL_TEXTURE0);GLES30.glBindTexture(GLES30.GL_TEXTURE_2D,color[0]);GLES30.glUniform1i(copy.uniform("uCloud"),0);GLES30.glDrawArrays(GLES30.GL_TRIANGLES,0,3);GLES30.glBindVertexArray(0);GLES30.glDepthMask(true);GLES30.glEnable(GLES30.GL_DEPTH_TEST);GLES30.glEnable(GLES30.GL_BLEND);GLES30.glEnable(GLES30.GL_CULL_FACE);}
 private void releaseBuffer(){if(color[0]!=0)GLES30.glDeleteTextures(1,color,0);if(fbo[0]!=0)GLES30.glDeleteFramebuffers(1,fbo,0);color[0]=fbo[0]=0;}
 public void release(){releaseBuffer();volume.release();copy.release();GLES30.glDeleteTextures(1,noise,0);GLES30.glDeleteVertexArrays(1,vao,0);}
 private static final String VERTEX="out vec2 vUv;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));vUv=p;gl_Position=vec4(p*2.0-1.0,0.0,1.0);}";
 private static final String COPY="precision highp float;in vec2 vUv;uniform sampler2D uCloud;out vec4 fragColor;void main(){fragColor=texture(uCloud,vUv);}";
 private static final String FRAGMENT="precision highp float;precision highp sampler3D;in vec2 vUv;out vec4 fragColor;uniform mat4 uInverse;uniform vec3 uCamera;uniform float uTime;uniform int uSteps;uniform sampler3D uNoise;"+
 "float density(vec3 p){vec3 q=p*.006+vec3(uTime*.0008,0.0,uTime*.00025);float n=texture(uNoise,q).r*.62+texture(uNoise,q*2.03).r*.26+texture(uNoise,q*4.01).r*.12;float h=(p.y-68.0)/68.0;return max(0.0,n-.47)*3.8*smoothstep(0.0,.22,h)*(1.0-smoothstep(.62,1.0,h));}"+
 "void main(){vec4 farPoint=uInverse*vec4(vUv*2.0-1.0,1.0,1.0);vec3 rd=normalize(farPoint.xyz/farPoint.w-uCamera);vec3 light=normalize(vec3(-.40,.17,.88));float disk=smoothstep(.99955,.99990,dot(rd,light));vec3 sky=mix(vec3(.045,.028,.045),vec3(.009,.012,.025),max(rd.y,0.0));sky+=vec3(.28,.065,.035)*disk+vec3(.05,.008,.012)*pow(max(dot(rd,light),0.0),25.0);float trans=1.0;vec3 cloud=vec3(0.0);if(rd.y>.006){float start=max(0.0,(68.0-uCamera.y)/rd.y),end=min(2000.0,(136.0-uCamera.y)/rd.y);float stepSize=max(0.0,end-start)/float(uSteps);float jitter=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453);for(int i=0;i<32;i++){if(i>=uSteps||trans<.015)break;vec3 p=uCamera+rd*(start+(float(i)+jitter)*stepSize);float d=density(p),alpha=1.0-exp(-d*stepSize*.065),shadow=exp(-density(p+light*17.0)*2.5);vec3 illumination=vec3(.068,.058,.078)+vec3(.21,.045,.032)*shadow;cloud+=trans*alpha*illumination;trans*=1.0-alpha;}}fragColor=vec4(cloud+sky*trans,1.0);}";
}
