package com.danil.blackswordsman;
import java.util.*;
/** Plants are anchored living geometry; harvesting creates effects, and regrowth is persisted. */
public final class FloraWorld implements java.io.Serializable {
 private static final long serialVersionUID=8L;
 public static final class Plant implements java.io.Serializable {private static final long serialVersionUID=8L;public long id;public int species;public float x,y,z,scale,yaw,bend;}
 public final ArrayList<Plant> plants=new ArrayList<Plant>();public final HashMap<Long,Float> harvested=new HashMap<Long,Float>();
 private int cx=Integer.MIN_VALUE,cz=Integer.MIN_VALUE;public float clock;public String hint="";private Plant nearest;
 public void reset(){plants.clear();harvested.clear();cx=cz=Integer.MIN_VALUE;clock=0;hint="";nearest=null;}
 public boolean visible(Plant p){Float until=harvested.get(p.id);return until==null||until<=clock;}
 public void stream(GameWorld w){int x=(int)Math.floor(w.player.x/24),z=(int)Math.floor(w.player.z/24);if(x==cx&&z==cz)return;cx=x;cz=z;plants.clear();int env=w.currentChapter().environment;for(int iz=z-1;iz<=z+1;iz++)for(int ix=x-1;ix<=x+1;ix++){Random r=new Random(ix*73856093L^iz*19349663L^env*83492791L^808);boolean forest=FloraCatalog.forest(env,ix*24+12,iz*24+12);int fungi=forest?64:24,count=fungi+(forest?26:14);for(int n=0;n<count;n++){float px=(ix+r.nextFloat())*24,pz=(iz+r.nextFloat())*24;if(Math.abs(px)>GameWorld.WORLD_HALF-3||Math.abs(pz)>GameWorld.WORLD_HALF-3||WaterField.depth(env,px,pz)>.08f||RegionLayout.reserved(px,pz)||Math.abs(px-WorldLayout.road(pz))<5.5f&&Math.abs(pz)<132||Math.abs(px)<9&&Math.abs(pz-66)<8)continue;int region=FloraCatalog.region(env,px,pz),id=n<fungi?FloraCatalog.select(env,px,pz,r):FloraCatalog.plant(region,r);if(n<fungi&&r.nextFloat()<.065f)id=24+(region*2+r.nextInt(3))%8;add((((long)(ix+128))<<32)|((long)(iz+128)<<16)|n,id,px,pz,.42f+r.nextFloat()*.45f,r.nextFloat()*360,w);}}
 // A discoverable ring offers all powers near the opening, without changing story objectives.
 for(int i=0;i<8;i++){float px=10+i%4*3.2f,pz=5+i/4*4;if(Math.abs(px-w.player.x)<40&&Math.abs(pz-w.player.z)<40&&WaterField.depth(env,px,pz)<.08f)add(-100-i,24+i,px,pz,.9f,i*43,w);}}
 private void add(long id,int species,float x,float z,float scale,float yaw,GameWorld w){Plant p=new Plant();p.id=id;p.species=species;p.x=x;p.z=z;p.y=w.physics.terrainHeight(x,z);p.scale=scale*(species>=32?1.3f:1);p.yaw=yaw;plants.add(p);}
 public void update(GameWorld w,float dt){clock+=dt;stream(w);nearest=null;float near=1.8f;for(Plant p:plants){if(!visible(p))continue;float dx=p.x-w.player.x,dz=p.z-w.player.z,d=(float)Math.sqrt(dx*dx+dz*dz);float target=Math.max(0,1-d/1.1f);for(GameWorld.Actor a:w.enemies)if(!a.dead&&Math.abs(a.x-p.x)<.8f&&Math.abs(a.z-p.z)<.8f)target=1;p.bend+=(target-p.bend)*Math.min(1,dt*9);if(p.species<32&&d<near&&Math.abs(w.player.y-p.y)<1.8f){near=d;nearest=p;}}if(nearest!=null){PhysicsWorld.Body body=w.physics.grabCandidate(w.player);if(w.physics.getHeld()!=null||body!=null&&(float)Math.sqrt((body.x-w.player.x)*(body.x-w.player.x)+(body.z-w.player.z)*(body.z-w.player.z))<near+.35f||w.physics.raycast(w.player.x,w.player.y+w.player.height*.65f,w.player.z,nearest.x,nearest.y+.4f,nearest.z,.02f,null,false)<.99f)nearest=null;}hint=nearest==null?"":FloraCatalog.NAMES[nearest.species]+" · ДЕЙСТВИЕ";if(harvested.size()>4096){Iterator<Map.Entry<Long,Float>> it=harvested.entrySet().iterator();while(it.hasNext())if(it.next().getValue()<=clock)it.remove();}}
 public boolean interact(GameWorld w){if(w.physics.getHeld()!=null||nearest==null||!visible(nearest))return false;Plant p=nearest;harvested.put(p.id,clock+180);if(p.species>=24){w.mushrooms.activate(p.species-24,w);w.banner=FloraCatalog.NAMES[p.species]+" · "+MushroomEffects.NAMES[p.species-24];}else{w.player.hp=Math.min(w.player.maxHp,w.player.hp+3);w.banner=FloraCatalog.NAMES[p.species]+" · +3 HP";}w.bannerTime=3;float[] c=FloraCatalog.color(p.species);w.astralBurst(p.x,p.y+.4f,p.z,c[0],c[1],c[2],12);nearest=null;hint="";return true;}
}
