package com.danil.blackswordsman;
import java.io.*;
/** Original tileable albedo / tangent-normal / roughness materials, baked at build time. */
public final class SurfaceLibrary {
 public static final int SKIN=0,CLOTH=1,LEATHER=2,METAL=3,SCALES=4,FUR=5,BARK=6,ASTRAL=7,MOSS=8,STONE=9,FUNGUS=10,LEAF=11,COUNT=12,SIDE=512;
 public static final String[] NAMES={"skin","cloth","leather","metal","scales","fur","bark","astral","moss","stone","fungus","leaf"};
 private static float noise(int x,int y,int seed){x=(x+SIDE)%SIDE;y=(y+SIDE)%SIDE;int n=x*374761393+y*668265263+seed*1442695041;n=(n^(n>>>13))*1274126177;return (n&65535)/65535f;}
 private static float height(int k,int x,int y){float u=x/(float)SIDE,v=y/(float)SIDE,n=noise(x,y,k),a=(float)Math.sin(u*6.2831853f*32),b=(float)Math.sin(v*6.2831853f*32);switch(k){case SKIN:return .45f+n*.09f+.025f*a*b;case CLOTH:return .5f+.19f*a*b+.05f*n;case LEATHER:return .25f+.20f*n+.04f*(float)Math.sin((u+v)*6.2831853f*11);case METAL:return .5f+.04f*n+.08f*(float)Math.sin(v*6.2831853f*110);case SCALES:float row=(y/32)%2;return .35f+.27f*(float)(Math.cos(u*6.2831853*16+row*Math.PI)*Math.sin(v*6.2831853*16));case FUR:return .4f+.14f*(float)Math.sin(u*6.2831853f*90+.8f*b)+.04f*n;case BARK:return .35f+.28f*(float)Math.sin(u*6.2831853f*13+2*b)+.08f*n;case ASTRAL:return .5f+.1f*(float)Math.sin((u+v)*6.2831853f*4)+.09f*a*b;case MOSS:return .35f+.30f*n+.08f*a*b;case STONE:return .35f+.15f*n+.10f*(float)Math.sin((u-v)*6.2831853f*5);case FUNGUS:return .5f+.08f*n+.14f*(float)Math.sin(u*6.2831853f*45);default:return .3f+.08f*n+.25f*Math.max(0,1-Math.abs(a)*5)+.08f*b;}}
 public static byte[][] layer(int k){int n=SIDE*SIDE;byte[] color=new byte[n*4],normal=new byte[n*4];float[] heights=new float[n];for(int y=0;y<SIDE;y++)for(int x=0;x<SIDE;x++)heights[y*SIDE+x]=height(k,x,y);for(int y=0;y<SIDE;y++)for(int x=0;x<SIDE;x++){int at=(y*SIDE+x)*4;float h=heights[y*SIDE+x],nx=(heights[y*SIDE+(x+SIDE-1)%SIDE]-heights[y*SIDE+(x+1)%SIDE])*1.5f,ny=(heights[((y+SIDE-1)%SIDE)*SIDE+x]-heights[((y+1)%SIDE)*SIDE+x])*1.5f,l=(float)Math.sqrt(1+nx*nx+ny*ny);float tone=.65f+h*.45f;color[at]=(byte)(255*Math.min(1,tone));color[at+1]=(byte)(255*Math.min(1,tone*(k==SKIN?.93f:k==BARK?.86f:1)));color[at+2]=(byte)(255*Math.min(1,tone*(k==SKIN?.88f:k==LEAF?.9f:1)));color[at+3]=(byte)(220+35*h);normal[at]=(byte)(127.5f+127.5f*nx/l);normal[at+1]=(byte)(127.5f+127.5f*ny/l);normal[at+2]=(byte)(127.5f+127.5f/l);normal[at+3]=(byte)(k==METAL?64+h*55:k==ASTRAL?80:130+h*110);}return new byte[][]{color,normal};}
 public static void bake(File assets)throws IOException{File dir=new File(assets,"materials");dir.mkdirs();for(int k=0;k<COUNT;k++){byte[][] data=layer(k);for(int c=0;c<2;c++){File dest=new File(dir,NAMES[k]+(c==0?"-color.rgba":"-normal.rgba")),part=new File(dest+".part");OutputStream out=new BufferedOutputStream(new FileOutputStream(part));out.write(data[c]);out.close();if(!part.renameTo(dest))throw new IOException("Material rename failed");}}}
 public static int actor(int type,int bone){if(type<0)return bone==3||bone==6?SKIN:bone==9?METAL:bone<3?METAL:CLOTH;if(type==GameWorld.SERPENT_SPAWN||type==GameWorld.SNAKE_BARON)return SCALES;if(type==GameWorld.FLESH_HOUND||type==GameWorld.TUSK_BOAR)return FUR;if(CreatureSystem.category(type)==CreatureSystem.MECHANICAL)return METAL;if(type==GameWorld.GROVE_WARDEN)return BARK;if(type==GameWorld.WRAITH||type==GameWorld.SHADE||type==GameWorld.STORM_SPIRIT)return ASTRAL;if(type==GameWorld.COUNT_APOSTLE||type==GameWorld.VOID_BEAST||type==GameWorld.GHOUL||type==GameWorld.ALIEN)return SKIN;return bone==3||bone==6||bone==9?SKIN:bone<3?LEATHER:CLOTH;}
 private SurfaceLibrary(){}
}
